env:
  TERM: xterm-256color

window:
  padding:
    x: 6
    y: 6
  dimensions:
    columns: 120
    lines: 70
  decorations: full
  opacity: 0.90

font:
  size: 12.0

colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'
  search:
    matches:
      foreground: '#ffffff'
      background: '#555555'
    focused_match:
      foreground: '#ffffff'
      background: '#777777'
  normal:
    black: '#000000'
    red: '#ff0000'
    green: '#0aef0a'
    yellow: '#ffff00'
    blue: '#0066ff'
    magenta: '#ff00aa'
    cyan: '#00aaff'
    white: '#ffffff'
  bright:
    black: '#777777'
    red: '#ff0000'
    green: '#0aef0a'
    yellow: '#ffff00'
    blue: '#0066ff'
    magenta: '#ff00aa'
    cyan: '#00aaff'
    white: '#ffffff'

key_bindings:
  - { key: F, mods: Command|Control, action: ToggleSimpleFullScreen }
